apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: oliverlittle.azurecr.io/orchestrator:latest
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: cassandra
          mountPath: "/etc/cassandra"
          readOnly: true
        env:
        - name: CASSANDRA_URL
          value: "demo-dc1-service"
        - name: CASSANDRA_DATACENTER
          value: "dc1"
        - name: CASSANDRA_USERNAME_FILE
          value: "/etc/cassandra/username"
        - name: CASSANDRA_PASSWORD_FILE"
          value: "/etc/cassandra/password"
      volumes:
        - name: cassandra
          secret:
            secretName: demo-superuser
            optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      nodePort: 30021
      port: 50051
      targetPort: 50051