apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: oliverlittle.azurecr.io/worker:latest
        ports:
        - containerPort: 50052
        volumeMounts:
        - name: cassandra
          mountPath: "/etc/cassandra"
          readOnly: true
        env:
        - name: CASSANDRA_URL
          value: "demo-dc1-service"
        - name: CASSANDRA_DATACENTER
          value: "dc1"
        - name: CASSANDRA_USERNAME_FILE
          value: "/etc/cassandra/username"
        - name: CASSANDRA_PASSWORD_FILE
          value: "/etc/cassandra/password"
      volumes:
        - name: cassandra
          secret:
            secretName: demo-superuser
            optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052