apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  serviceName: "worker-service"
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: oliverlittle.azurecr.io/worker:latest
        ports:
        - containerPort: 50052
          name: worker
        resources:
          requests:
            cpu: 1
            memory: 4Gi
          limits:
            cpu: 1.5
            memory: 6Gi
        volumeMounts:
        - name: cassandra
          mountPath: "/etc/cassandra"
          readOnly: true
        env:
        - name: CASSANDRA_DATACENTER
          value: "dc1"
        - name: CASSANDRA_USERNAME_FILE
          value: "/etc/cassandra/username"
        - name: CASSANDRA_PASSWORD_FILE
          value: "/etc/cassandra/password"
        - name: CASSANDRA_BASE_URL
          value: "demo-dc1-all-pods-service"
        - name: NUM_CASSANDRA_NODES
          value: "3"
        - name: CASSANDRA_NODE_NAME
          value: "demo-dc1-default-sts"
      volumes:
        - name: cassandra
          secret:
            secretName: demo-superuser
            optional: false
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: cassandra.datastax.com/cluster
                  operator: In
                  values:
                  # This must be the same name as the Cassandra cluster
                  - demo
                - key: cassandra.datastax.com/datacenter
                  operator: In
                  values:
                  # This must be the same name as the Cassandra datacenter name
                  - dc1
              topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker
              topologyKey: topology.kubernetes.io/zone
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: worker
  ports:
    - port: 50052
      name: worker