# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import client_query_pb2 as client__query__pb2


class TableClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeTable = channel.unary_unary(
                '/TableClientService/ComputeTable',
                request_serializer=client__query__pb2.ComputeTableRequest.SerializeToString,
                response_deserializer=client__query__pb2.ComputeTableResult.FromString,
                )


class TableClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeTable': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeTable,
                    request_deserializer=client__query__pb2.ComputeTableRequest.FromString,
                    response_serializer=client__query__pb2.ComputeTableResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TableClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TableClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TableClientService/ComputeTable',
            client__query__pb2.ComputeTableRequest.SerializeToString,
            client__query__pb2.ComputeTableResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)