# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import table_model_pb2 as table__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63lient_query.proto\x1a\x11table_model.proto\",\n\x13\x43omputeTableRequest\x12\x15\n\x05table\x18\x01 \x01(\x0b\x32\x06.Table2R\n\x12TableClientService\x12<\n\x0c\x43omputeTable\x12\x14.ComputeTableRequest\x1a\x14.StreamedTableResult0\x01\x42!\n\x1forg.oliverlittle.clusterprocessb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.oliverlittle.clusterprocess'
  _COMPUTETABLEREQUEST._serialized_start=41
  _COMPUTETABLEREQUEST._serialized_end=85
  _TABLECLIENTSERVICE._serialized_start=87
  _TABLECLIENTSERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)