# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import client_query_pb2 as client__query__pb2
from . import table_model_pb2 as table__model__pb2


class TableClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTable = channel.unary_unary(
                '/TableClientService/SendTable',
                request_serializer=table__model__pb2.Table.SerializeToString,
                response_deserializer=client__query__pb2.TableComputeResult.FromString,
                )


class TableClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTable': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTable,
                    request_deserializer=table__model__pb2.Table.FromString,
                    response_serializer=client__query__pb2.TableComputeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TableClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TableClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TableClientService/SendTable',
            table__model__pb2.Table.SerializeToString,
            client__query__pb2.TableComputeResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
