apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: test
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                memory: 2Gi
                storage: 4Gi
              limits:
                memory: 4Gi
        config:
          jvmOptions:
            heapSize: 512M
  stargate:
    size: 1
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 1Gi
    heapSize: 256Mi
    allowStargateOnDataNodes: true
