kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
  - containerPort: 30942
    hostPort: 30942
    protocol: TCP
- role: worker
# k8ssandra also adds the following configurations for each worker:
# kubeadmConfigPatches:
#     - |
#       kind: JoinConfiguration
#       nodeRegistration:
#         kubeletExtraArgs:
#           node-labels: "topology.kubernetes.io/zone=region$((${cluster_id}+1))-zone$(( (${i} % 3) +1))"