name: ACR_Push

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login to Azure Container Registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            
        - name: 'Generate and push worker container'
          working-directory: ./server/worker
          run: |
            sbt docker:publishLocal 
            docker tag worker:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:latest
            
        - name: 'Generate and push orchestrator container'
          working-directory: ./server/orchestrator
          run: |
            sbt docker:publishLocal 
            docker tag worker:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/orchestrator:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/orchestrator:latest
