on:
  workflow_dispatch

jobs:  
 deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: 'Generate and push python container'
      working-directory: ./python_client
      run: |
        docker build --tag python_client:latest .
        docker tag python_client:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/python_client:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/python_client:latest
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: 'Generate and push worker container'
      working-directory: ./server/worker
      run: |
        sbt docker:publishLocal 
        docker tag worker:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/worker:latest
    - name: 'Generate and push orchestrator container'
      working-directory: ./server/orchestrator
      run: |
        sbt docker:publishLocal 
        docker tag orchestrator:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/orchestrator:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/orchestrator:latest